### PR TITLE
Add mocha tests conversion to async/await

### PR DESCRIPTION
**Pull request by dwickern**
Converts from the `andThen` style acceptance tests...
```js
it('can visit subroutes', function(done) {
  visit('/');

  andThen(function() {
    expect(find('h2').text()).to.be.empty;
  });

  visit('/foo');

  andThen(function() {
    expect(find('h2').text()).to.be.equal('this is an acceptance test');
    done();
  });
});
```
... into cleaner async/await style:
```js
it('can visit subroutes', async function() {
  await visit('/');

  expect(find('h2').text()).to.be.empty;

  await visit('/foo');

  expect(find('h2').text()).to.be.equal('this is an acceptance test');
});
```

I only implemented mocha since that's what I use, but qunit could be added ([ember-power-select](https://github.com/cibernox/ember-power-select/blob/master/tests/acceptance/helpers-test.js) has some example qunit tests using async/await style).

It doesn't handle custom async test helpers which need to be awaited. Maybe there could be a config option to list the names of additional async helpers.

It doesn't handle naming/scoping conflicts when merging `andThen` blocks. Babel will catch them if the code is invalid (e.g. reassign to `const`), otherwise the linter will catch them. For example:
```js
andThen(function() {
  let foo = 1;
});
andThen(function() {
  let foo = 2;
});

// will become:
let foo = 1;
let foo = 2;
```
\

### CODE REVIEW

**Comment by knownasilya** [comment]
I updated Travis and rebased this branch. Just waiting on Travis to finish its thing.

Would be nice to have this for QUnit, since that's probably more widely used since it's the default. Otherwise, this looks A+

**Comment by knownasilya** [comment]
@dwickern could you update the README.md with your command. Just follow how the other commands are documented. Once that's done, I'll be happy to merge. Thanks again!

**Comment by dwickern** [comment]
I updated the readme. It was easy to add qunit support too, although I haven't run it against an actual qunit project

**Comment by knownasilya** [comment]
Beautiful!

**Comment by knownasilya** [comment]
Published as v0.9.0

**Pull request merged**
