### PR TITLE
add CP Spread test

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
@abuiles ping

**Comment by fivetanley** [comment]
needs a rebase and also travis failed.

**Comment by stefanpenner** [comment]
> needs a rebase and also travis failed.

@fivetanley this is a failing test

**Comment by stefanpenner** [comment]
[edit: updated title]

**Comment by knownasilya** [comment]
This should probably be merged, right?

**Comment by stefanpenner** [comment]
@knownasilya i think we are still waiting for it to be fixed.

**Comment by knownasilya** [comment]
The test will tell us if it's been fixed, but first you need to have the test present :smile:

**Pull request closed without merging**
