### PR TITLE
Fix async-false-relationships action

### PR DESCRIPTION
**Pull request by knownasilya**

### CODE REVIEW

**Comment by stefanpenner** [comment]
does this need a test?

**Comment by knownasilya** [comment]
The cli stuff needs tests in general, since there are none.

**Comment by abuiles** [comment]
@stefanpenner @knownasilya correct, I've been ignoring that, but I think is time to do it, we had to issues related with that in the last release.

@knownasilya do you mind giving us a hand with that :) ?

**Comment by stefanpenner** [comment]
> The cli stuff needs tests in general, since there are none.

ah... cc @abuiles

**Comment by abuiles** [comment]
@stefanpenner I'm aware of this, checking with @knownasilya if he can give a hand with this.. otherwise I can start looking later.

**Comment by knownasilya** [comment]
@abuiles I'll work on a PR.

**Comment by abuiles** [comment]
@knownasilya awesome! thank you very much

**Pull request merged**
